In [6]:
import pandas as pd

# read in dataset
xl = pd.ExcelFile("data/130N_Cycles_1-47.xlsx")
df = xl.parse("Specimen_RawData_1")
df

           Time     Load
0         (sec)      (N)
1             0  0.06729
2        0.0018  0.07128
3           0.1  0.05453
4           0.2  0.00621
5           0.3  0.00352
6           0.4  0.02063
7           0.5 -0.00168
8           0.6 -0.01183
9           0.7 -0.00167
10          0.8 -0.00656
11          0.9 -0.02108
12            1 -0.03623
13          1.1 -0.02316
14          1.2 -0.05095
15          1.3 -0.07705
16          1.4 -0.05499
17          1.5 -0.04504
18          1.6 -0.06794
19          1.7 -0.10153
20          1.8 -0.05887
21          1.9 -0.06541
22            2 -0.07291
23          2.1 -0.03818
24          2.2 -0.04398
25          2.3  0.00392
26          2.4 -0.02976
27          2.5  0.01042
28          2.6  0.02127
29          2.7 -0.01094
...         ...      ...
170072    16768 -0.13978
170073  16768.1 -0.12339
170074  16768.2 -0.15841
170075  16768.3 -0.12322
170076  16768.4 -0.11189
170077  16768.5 -0.12804
170078  16768.6 -0.11056
170079  16768.7 -0.09291
170080  16768.8 -0.08599
170081  16768.9 -0.10398
170082    16769 -0.08131
170083  16769.1 -0.05598
170084  16769.2 -0.07377
170085  16769.3 -0.09031
170086  16769.4 -0.04457
170087  16769.5 -0.03088
170088  16769.6 -0.03074
170089  16769.7 -0.04886
170090  16769.8 -0.01057
170091  16769.9 -0.03553
170092    16770 -0.01936
170093  16770.1   0.0022
170094  16770.2  0.02822
170095  16770.3  0.02014
170096  16770.4  0.02088
170097  16770.5  0.05239
170098  16770.6  0.03399
170099  16770.7  0.05024
170100  16770.8  0.06006
170101  16770.9  0.09558

[170102 rows x 2 columns]